# Basic Build and Publish of Image with Buildx and collecting Build Info from the build metadata


name: 'Basic Build, Publish & Build Info: Buildx'
on:
  workflow_dispatch:

permissions:
  id-token: write
  security-events: write
  attestations: write

env:
  DOCKER_REPOSITORY: 'imagelifecycle-docker-local'
  IMAGE_NAME: 'hello-frog'
  IMAGE_METADATA_FILENAME: 'metadata.json'
  BUILD_NAME: 'docker-buildx-info-example'


jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Setup JF CLI
        id: jfrog-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
        with:
          version: 'latest'
          oidc-provider-name: 'github-oidc-integration'
          oidc-audience: 'jfrog-github'
          disable-auto-build-publish: true

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JF_DOCKER_REGISTRY }}
          username: ${{ steps.jfrog-cli.outputs.oidc-user }}
          password: ${{ steps.jfrog-cli.outputs.oidc-token }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          provenance: true
          push: true
          tags: ${{ vars.JF_DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY}}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

      - name: Create Metadata File
        env:
          # This maps the JSON string safely to an env var
          BUILD_METADATA: ${{ steps.build-and-push.outputs.metadata }}
        run: |
          # Use the env var, quoted, to pipe into a file
          echo "$BUILD_METADATA" > ${{ env.IMAGE_METADATA_FILENAME }}

      - name: Validate Metadata File (Optional)
        run: |
          # Using jq to verify it's valid JSON and pretty-print it
          cat ${{ env.IMAGE_METADATA_FILENAME }} | jq .

      - name: Validate Metadata File Content
        run: |
         cat ${{ env.IMAGE_METADATA_FILENAME }}

      # Until this is more elegantly supported, we manually create the image metadata file.  Note the format is:
      # <registry>/<image-name>:<tag>@<digest>
      # repository is not part of the image name in this context., see the jf rt build-docker-create command below.
      - name: Create Image Metadata File
        run: |
          echo "${{ vars.JF_DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}@${{ steps.build-and-push.outputs.digest }}" > ${{ env.IMAGE_METADATA_FILE }}

      - name: Display Image MetadataFile
        run: |
          cat ${{ env.IMAGE_METADATA_FILE }}  

      - name: Docker Build Info
        run: |
          jf rt build-docker-create \
          ${{ env.DOCKER_REPOSITORY}} \
          --build-name=${{ env.BUILD_NAME }} \
          --build-number=${{ github.run_number }} \
          --image-file ${{ env.IMAGE_METADATA_FILENAME }} \

      - name: Publish Build Info
        run: |
          jf rt build-publish ${{ env.BUILD_NAME }} ${{ github.run_number }}
          
