name: 'Basic Build and Publish with Attestation: Docker'
on:
  workflow_dispatch:

permissions:
  id-token: write
  security-events: write
  attestations: write

env:
  DOCKER_REPOSITORY: 'imagelifecycle-docker-local'
  IMAGE_NAME: 'hello-frog'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Setup JF CLI
        id: jfrog-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
        with:
          version: 'latest'
          oidc-provider-name: 'github-oidc-integration'
          oidc-audience: 'jfrog-github'
          disable-auto-build-publish: true

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JF_DOCKER_REGISTRY }}
          username: ${{ steps.jfrog-cli.outputs.oidc-user }}
          password: ${{ steps.jfrog-cli.outputs.oidc-token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: push
        with:
          push: true
          tags: ${{ vars.JF_DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY}}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

      - name: Attest
        uses: actions/attest-build-provenance@v3
        id: attest
        with:
          subject-name: oci://${{ vars.JF_DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY}}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true